export enum OtpType {
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PHONE_VERIFICATION = 'PHONE_VERIFICATION',
  ORGANIZATION_INVITATION = 'ORGANIZATION_INVITATION',
  TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH',
}
